### ISSUE TITLE
Question: What's nostr_deno vs nostr_deno_client?

### ISSUE THREAD

**Issue by chmac** [KiPSOFT/nostr-deno#10]
Firstly, thanks for bringing nostr to deno, awesome work!

I found these two:

- https://deno.land/x/nostr_deno_client@v0.2.4
- https://deno.land/x/nostr_deno@v0.4.1

The first is a lower version number, but published more recently. The readme here links to the first.

Can you explain what the difference is? Or if one is deprecated is there any way to update its readme on deno.land?

**Comment by KiPSOFT** [comment]
Hi @chmac 

I created both of them. I created the nostr_deno module on deno.land, but then I had to delete the repo. However, there is no way to update or delete a module on deno.land. That's why I had to create a new module. The current module is nostr_deno_client.
