### ISSUE TITLE
Error with secp256k1 library

### ISSUE THREAD

**Issue by retog** [KiPSOFT/nostr-deno#5]
Running the example, I get the error

```
error: Relative import path "crypto" not prefixed with / or ./ or ../
    at https://deno.land/x/secp256k1@1.7.0/index.ts:6:29
```

**Comment by KiPSOFT** [comment]
Hi, retog. What's your deno version?

**Comment by retog** [comment]
Hi, just upgraded to1.29.1

**Comment by retog** [comment]
@KiPSOFT does it work with another deno version?

The comment at https://deno.land/x/secp256k1@1.7.0/index.ts?source#L5 suggests that the offending is being removed at build time. So maybe a built version could be imported instead of the source.

**Comment by KiPSOFT** [comment]
Sorry for the delay. I made some updates and bug fixes. You can now import it like this: 

```javascript
import { Nostr, Relay } from 'https://deno.land/x/nostr_deno_client@v0.2.0/mod.ts';
```

**Comment by retog** [comment]
Still the same issue with the node-style import of `crypto`.

```
> deno -V
deno 1.29.1
> deno run -A https://deno.land/x/nostr_deno_client@v0.2.0/nostr.ts
error: Relative import path "crypto" not prefixed with / or ./ or ../
    at https://deno.land/x/secp256k1@1.7.0/index.ts:6:29
```

**Comment by KiPSOFT** [comment]
Please change import url to https://deno.land/x/nostr_deno_client@v0.2.0/mod.ts

**Comment by retog** [comment]
I'm sorry. I missed the change of file. Thanks!
